<a href="https://colab.research.google.com/github/jayantika22/mini-project-1-python-/blob/main/mini_project_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
#Q1 L is defined as L = [11, 12, 13, 14]
# i) WAP to add 50 and 60 to L

L = [11, 12, 13, 14]
L.extend([50, 60])
print(L)

# ii) WAP to remove 13 and 11 from L
L = [11, 12, 13, 14]
L.remove(11)
L.remove(13)
print(L)

# iii) WAP to sort L in ascending order
L = [11, 12, 13, 14]
L.sort()
print(L)

# iv) WAP to sort L in descending order
L = [11, 12, 13, 14]
L.sort(reverse = True)
print(L)

# v) WAP to search for 13 in L
L = [11, 12, 13, 14]
if 13 in L:
  print ("13 is there")

# vi) WAP to count number of elements in L
L = [11, 12, 13, 14]
count = len(L)
print("Number of elements in L:", count)

# vii) WAP to add number of elements in L
L = [11, 12, 13, 14]
total = sum(L)
print("Sum of elements in L:", total)

# viii) WAP to add odd number elements in L
L = [11, 12, 13, 14]
odd_sum = 0

for num in L:
    if num % 2 != 0:  # Check if the number is odd
        odd_sum += num

print("Sum of odd elements in L:", odd_sum)

# ix) WAP to add even number elements in L
L = [11, 12, 13, 14]
even_sum = 0

for num in L:
  if num % 2 == 0:
    even_sum += 0

print("Sum of even elements in L:", even_sum)

# x) WAP to add prime number elements in L
L = [11, 12, 13, 14]
prime_sum = 0

for num in L:
    if num > 1:
        for i in range(2, num):
            if (num % i) == 0:
                break
            else:
                 prime_sum = prime_sum + num
                 print(prime_sum)


# xi) WAP to clear all elements in L
L = [11, 12, 13, 14]
L.clear()
print("List L after clearing all elements:", L)

# xii) WAP to delete L
L = [11, 12, 13, 14]
del L

[11, 12, 13, 14, 50, 60]
[12, 14]
[11, 12, 13, 14]
[14, 13, 12, 11]
13 is there
Number of elements in L: 4
Sum of elements in L: 50
Sum of odd elements in L: 24
Sum of even elements in L: 0
11
22
33
44
55
66
77
88
99
112
125
138
151
164
177
190
203
216
229
242
List L after clearing all elements: []

In [11]:
#Q2 D is dictionery defined as D =  {1:5.6, 2:7.8, 3:6.6, 4:8.7, 5:7.7}

#i) WAP to add new entry in D; key = 8 and value is 8.8
D =  {1:5.6, 2:7.8, 3:6.6, 4:8.7, 5:7.7}
D[(8)] = 8.8
print(D)

#ii) WAP to remove key = 2
D =  {1:5.6, 2:7.8, 3:6.6, 4:8.7, 5:7.7}
del D[(2)]
print(D)

#iii) WAP to check whether 6 key present in D
D =  {1:5.6, 2:7.8, 3:6.6, 4:8.7, 5:7.7}
if len(D)==6:
  print("true")
else:
  print("false")

#iv) WAP to count number of elements  present in D
D =  {1:5.6, 2:7.8, 3:6.6, 4:8.7, 5:7.7}
printI = len(D)
print(printI)

#v) WAP to add all the values present in D
D =  {1:5.6, 2:7.8, 3:6.6, 4:8.7, 5:7.7}
total= sum(D)
print(total)

#vi) WAP to update value of 3 to 7.1
D =  {1:5.6, 2:7.8, 3:6.6, 4:8.7, 5:7.7}
D[3] = 7.1
print("Updated dictionary:", D)

#vii) WAP to clear the dictionery
D =  {1:5.6, 2:7.8, 3:6.6, 4:8.7, 5:7.7}
D.clear()
print("Dictionary D after clearing:", D)

{1: 5.6, 2: 7.8, 3: 6.6, 4: 8.7, 5: 7.7, 8: 8.8}
{1: 5.6, 3: 6.6, 4: 8.7, 5: 7.7}
false
5
15
Updated dictionary: {1: 5.6, 2: 7.8, 3: 7.1, 4: 8.7, 5: 7.7}
Dictionary D after clearing: {}

In [7]:
#Q3 S1 is a set defined as S1= [10, 20, 30, 40, 50, 60].
#   S2 is a set defined as S2= [40, 50, 60, 70, 80, 90].
#(i) WAP to add 55 and 66 in Set S1.
S1 = {10, 20, 30, 40, 50, 60}
S1.add(55)
S1.add(66)
print(S1)
#(ii) WAP to remove 10 and 30 from Set S1.
S1 = {10, 20, 30, 40, 50, 60}
S1.remove(10)
S1.remove(30)
print(S1)
#(iii) WAP to check whether 40 is present in S1.
S1 = {10, 20, 30, 40, 50, 60}
if 40 in S1:
    print("40 is present in S1")
else:
    print("40 is not present in S1")

#(iv) WAP to find the union between S1 and S2.
S1 = {10, 20, 30, 40, 50, 60}
S2 = {40, 50, 60, 70, 80, 90}
print(S1.union(S2))

#(v) WAP to find the intersection between S1 and S2.
S1 = {10, 20, 30, 40, 50, 60}
S2 = {40, 50, 60, 70, 80, 90}
print(S1.intersection(S2))
#(vi) WAP to find the S1 - S2.
S1 = {10, 20, 30, 40, 50, 60}
S2 = {40, 50, 60, 70, 80, 90}
difference = S1 - S2
print("Set difference S1 - S2:", difference)

{50, 66, 20, 55, 40, 10, 60, 30}
{50, 20, 40, 60}
40 is present in S1
{70, 40, 10, 80, 50, 20, 90, 60, 30}
{40, 50, 60}

In [4]:
#Q4. Write the following program.
#(i) WAP to print 100 random strings whose length between 6 and 8.
import string as s
import random as r

for i in range(100):
    j = r.randint(6,8)
    print("".join(r.sample(s.ascii_letters,j))+"\n")


#(ii) WAP to print all prime numbers between 600 and 800.
for num in range(600, 801):
    if num > 1:
        for i in range(2, num):
            if (num % 1) == 0:
                break
            else:
              print (num)







#(iii) WAP to print all numbers between 100 and 1000 that are divisible by 7 and 9.
for num in range(100, 1000):
    if num % 7 == 0 and num % 9 == 0:
        print(num)

FodvjVJc

vXsTKw

HNGYToO

VPqOCzIU

Chajxd

RueMVB

joMONtgu

xiIUprN

nemObqAB

ldLTOW

JRNFOyMr

wCKOWE

AZyJKz

nMmQEpBI

mrAxUuVS

eIRpxLw

eCuYgj

tkxuAh

aPZxnRXz

Gavzwpy

xYKDJmM

OmWADl

cRAjDyHS

MKxPDa

xSaUjC

ubOEPQ

rdYIjVK

dAsgpNI

baTyBlO

fNHAMT

zdZKcWw

nwWYSVd

OCzNoFEx

ksfvTAtP

fyvKeMJ

gquJKB

uoBIqfDs

ZwlOsi

lDyhYQM

pZDWQiY

BUnsQNe

TKRDioc

NXKITMre

JqIBywu

RwgYviXN

NmTwiUp

jRtIgMs

EUNxnYjh

Cbjvrfo

vfIkmjhR

Mydforzg

ULRgrtQA

UXEPzoT

vMrFPkTW

qWxCltj

MSYeZWB

vaGNkR

qbACnLP

JpQjoxuL

KDPhjX

UfAZwsCv

jcLmDE

ziyHOLxt

hkWLyncb

GvVCSm

BHUFKOv

VKRmrNCo

LXxbSsa

sEYjIvc

RWYnezT

NbUksg

IGnqDd

CzUAdR

vFirmSCu

VUyjNcTp

GRvehY

gMVpNfrZ

CguZQBTc

sOMTfHuY

EVmhnjP

ouLUIMn

ablVMtvr

OHQjKt

tvDczu

fkKzyoeX

HGtkziOF

TvUfRteS

uBNFIOK

gNsyHzF

YjPmkpL

ODEXynl

NiqWoV

hysjZR

SfaRlM

AFJtlx

IkLabuB

dbxpFKHW

CkOoFNXS

QepvJna

LqAipn

126
189
252
315
378
441
504
567
630
693
756
819
882
945

In [12]:
#Q5. WAP to create two lists of 10 random numbers between 10 and 30; Find
import random as r
L1 = print (r.sample(range(10,30),10))
L2 = print (r.sample(range(10,30),10))

#(i) Common numbers in the two lists
L1 =[25, 12, 29, 23, 18, 24, 27, 14, 19, 20]
L2 = [22, 11, 27, 26, 10, 18, 20, 19, 15, 24]
set1 = set(L1)
set2 = set(L2)

common_numbers = set1.intersection(set2)

print("Common numbers:", common_numbers)


#(ii) Unique numbers in both the list
L1 =[25, 12, 29, 23, 18, 24, 27, 14, 19, 20]
L2 = [22, 11, 27, 26, 10, 18, 20, 19, 15, 24]
set1 = set(L1)
set2 = set(L2)

print(set2 - set1)
#(iii) Minimum in both the list
print(min(L1))
print(min(L2))
#(iv) Maximum in both the list
print(max(L1))
print(max(L2))
#(v) Sum of both the lists
L1 =[25, 12, 29, 23, 18, 24, 27, 14, 19, 20]
L2 = [22, 11, 27, 26, 10, 18, 20, 19, 15, 24]

L3 = print(L1 + L2)

[13, 23, 10, 24, 15, 20, 18, 19, 12, 21]
[13, 24, 22, 14, 27, 26, 20, 29, 16, 12]
Common numbers: {18, 19, 20, 24, 27}
{10, 11, 15, 22, 26}
12
10
29
27
[25, 12, 29, 23, 18, 24, 27, 14, 19, 20, 22, 11, 27, 26, 10, 18, 20, 19, 15, 24]

In [25]:
#Q6. WAP to create a list of 100 random numbers between 100 and 900. Count and print the:

#(i) All odd numbers
import random
L1 = random.sample(range(100, 900), 100)

print("List of random numbers:", L1)

for num in L1:
    if num % 2 != 0:
        print(num)
#(ii) All even numbers
for num in L1:
    if num % 2 == 0:
        print(num)

#(iii) All prime numbers
for num in L1:
    if num > 1:
        for i in range(2, num):
            if (num % i) == 0:
                break
            else:
              print(num)

List of random numbers: [217, 347, 700, 523, 147, 335, 616, 779, 346, 535, 692, 624, 650, 180, 851, 470, 486, 113, 258, 464, 703, 377, 460, 238, 237, 858, 190, 197, 396, 195, 401, 684, 265, 511, 726, 136, 417, 297, 199, 143, 596, 857, 580, 374, 630, 349, 286, 889, 163, 462, 254, 869, 601, 548, 369, 820, 578, 209, 461, 110, 634, 893, 554, 166, 582, 638, 287, 526, 201, 875, 338, 241, 711, 278, 455, 757, 120, 144, 327, 134, 610, 329, 644, 641, 178, 157, 438, 719, 192, 807, 854, 303, 825, 551, 207, 291, 716, 885, 182, 847]
217
347
523
147
335
779
535
851
113
703
377
237
197
195
401
265
511
417
297
199
143
857
349
889
163
869
601
369
209
461
893
287
201
875
241
711
455
757
327
329
641
157
719
807
303
825
551
207
291
885
847
700
616
346
692
624
650
180
470
486
258
464
460
238
858
190
396
684
726
136
596
580
374
630
286
462
254
548
820
578
110
634
554
166
582
638
526
338
278
120
144
134
610
644
178
438
192
854
716
182

In [8]:
#Q7. D is a dictionary defined as D={1:"One",2:"Two",3:"Three",4:"Four", 5:"Five"}.
#WAP to read all the keys and values from dictionary and write to the file in the given below format.
#Key1, Value1
#Key2, Value2
#Key3, Value3
D={1:"One",2:"Two",3:"Three",4:"Four", 5:"Five"}
with open('output.txt', 'w') as file:
    for k in D:
       print(k,",", D[k])
file.close()

1 , One
2 , Two
3 , Three
4 , Four
5 , Five

In [9]:
#Q8. L is a list defined as L={"One","Two","Three","Four","Five"}.
#WAP to count the length of reach element from a list and write to the file in the given below format:
#One, 3
#Two, 3
#Four, 4
L={"One","Two","Three","Four","Five"}
with open('output.txt', 'w') as file:
    for k in L:
       print(k, ",", len(k))
file.close()

Four , 4
Five , 4
Two , 3
One , 3
Three , 5

In [16]:
#Q9. Write to the file 100 random strings whose length between 10 and 15.
import string as s
import random as r

with open('output.txt' , 'w') as file:
  for k in range(1,101):
      j = r.randint(10,16)
      file.write("".join(r.sample(s.ascii_letters,j))+"\n")
  file.close()

In [5]:
#Q10. Write to the file all prime numbers between 600 and 800.

with open('output.txt' , 'w') as file:
  for num in range(600, 801):
    if num > 1:
        for i in range(2, num):
            if (num % 1) == 0:
                break
            else:
              print (num)
              file.write(str(num)+"\n")
  file.close()

In [3]:
#Q11. WAP to calculate the time taken by a program.
import time
start_time = time.time()
total = 0
for i in range(1000000):
      total = total + i
end_time = time.time()

elapsed_time = end_time - start_time

print(f"Time taken by the program: {elapsed_time:.4f} seconds")

Time taken by the program: 0.1388 seconds

In [8]:
#Q12. WAP to sort following number of elements in a list, calculate time taken and plot the graph.
#Number of elements in list Time Taken
#5k T1
#10k T2
#15k T3
#20k T4
#25k T
L = [5000, 10000, 15000, 20000, 25000 ]
def ele_5000():
    L1 = [i for i in range(5000)]
    start_time = time.time()
    L1.sort()
    end_time = time.time()
    total = end_time - start_time
    print(f"{total:.4f}")
def ele_10000():
    L2 = [i for i in range(5000)]
    start_time = time.time()
    L2.sort()
    end_time = time.time()
    total = end_time - start_time
    print(f"{total:.4f}")
def ele_15000():
    L3 = [i for i in range(5000)]
    start_time = time.time()
    L3.sort()
    end_time = time.time()
    total = end_time - start_time
    print(f"{total:.4f}")
def ele_20000():
    L4 = [i for i in range(5000)]
    start_time = time.time()
    L4.sort()
    end_time = time.time()
    total = end_time - start_time
    print(f"{total:.4f}")
def ele_25000():
    L5 = [i for i in range(5000)]
    start_time = time.time()
    L5.sort()
    end_time = time.time()
    total = end_time - start_time
    print(f"{total:.4f}")

In [ ]:
#Q13. WAP to create a dictionary of student marks in five subjects and you have to find the student having maximum and minimum average marks.
D = {"maths": 90, "chemistry": 86, "hindi": 78, "english": 92, "physics": 50}
print(D)
print("MAX", max(D.values()))
print("MIN", min(D.values()))
print("AVG", sum(D.values())/len(D.values()))